name: End-to-End Test
on:
  schedule:
    - cron: "0 12 1 1 *"
  workflow_dispatch:
    inputs:
      cron:
        description: "Cron schedule expression"
        required: true
        default: "0 0 * * *"
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm ci
      - run: npm run build
      - uses: ./
        with:
          token: ${{ secrets.GR2M_PAT_WITH_WORKFLOW_SCOPE }}
          cron: ${{ github.event.inputs.cron }}
