on:
  schedule:
    - cron: "0 12 * * *"
name: Reminder
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm ci
      - run: npm run build
      - uses: ./
        with:
          crons: |
            0 12 * * *
            0 0 * * *
